#!/bin/bash
set -e

files=$(git diff --staged --name-only)

if [[ "$files" = *"pokemon.json"* ]]; then
	# Validate the JSON
	jsonlint -q pokemon.json

	# Regenerate the docs folder
	(cd docs && make)

	git add --update docs
fi
